sitkatech/projectfirma

Database/LookupTables/dbo.MeasurementUnitType.sql, Source/ProjectFirma.Web/Models/Generated/MeasurementUnitType.Binding.cs
Added to lookup table and gen-all run, units already alph sorted in PM editor
=> [projectfirma/#1094] Add acre-feet as Measurement Unit

Source/LtInfo.Common/DhtmlWrappers/DhtmlxGridHtmlHelpers.cs, Source/LtInfo.Common/DhtmlWrappers/GridSpec.cs, Source/ProjectFirma.Web/Controllers/PerformanceMeasureController.cs, Source/ProjectFirma.Web/Views/PerformanceMeasure/IndexViewData.cs
Added full excel download for PMs with Subcategories and Options
=> [projectfirma/#1098] Full PM Excel Download

Database/ReleaseScript/084 - Rename OrganizationAbbreviation to OrganizationShortName.sql, Database/Tables/dbo.Organization.sql, Source/ProjectFirma.Web/Common/FirmaValidationMessages.cs, Source/ProjectFirma.Web/Controllers/OrganizationController.cs, Source/ProjectFirma.Web/Controllers/UserController.cs, Source/ProjectFirma.Web/DatabaseEntities.csdl, Source/ProjectFirma.Web/DatabaseEntities.msl, Source/ProjectFirma.Web/DatabaseEntities.ssdl, Source/ProjectFirma.Web/Models/FundingSource.cs, Source/ProjectFirma.Web/Models/FundingSourceSimple.cs, Source/ProjectFirma.Web/Models/Generated/Organization.Binding.cs, Source/ProjectFirma.Web/Models/Organization.cs, Source/ProjectFirma.Web/Models/OrganizationModelExtensions.cs, Source/ProjectFirma.Web/Models/OrganizationSimple.cs, Source/ProjectFirma.Web/Service/ServiceModels/WebServiceOrganization.cs, Source/ProjectFirma.Web/Service/WebServicesTest.cs, Source/ProjectFirma.Web/UnitTestCommon/TestOrganization.cs, Source/ProjectFirma.Web/Views/Home/Index.cshtml, Source/ProjectFirma.Web/Views/Organization/Detail.cshtml, Source/ProjectFirma.Web/Views/Organization/Edit.cshtml, Source/ProjectFirma.Web/Views/Organization/EditViewModel.cs, Source/ProjectFirma.Web/Views/Organization/EditViewModelTest.cs, Source/ProjectFirma.Web/Views/Organization/EditViewModelValidator.cs, Source/ProjectFirma.Web/Views/Organization/IndexGridSpec.cs
Renamed OrganizationAbbreviation to OrganizationShortName and used OrganizationShortName on LMHT on Home page
=> [projectfirma/#1101] Show RCD boundaries on project maps

Database/LookupTables/dbo.FirmaPageType.sql, Database/ReleaseScript/089 - Add Firma Page for Home Page Map Intro Text.sql, Source/ProjectFirma.Web/Controllers/HomeController.cs, Source/ProjectFirma.Web/Models/FirmaPageType.cs, Source/ProjectFirma.Web/Models/Generated/FirmaPageType.Binding.cs, Source/ProjectFirma.Web/Views/Home/Index.cshtml, Source/ProjectFirma.Web/Views/Home/IndexViewData.cs
added Home map editable section release script/lookup table, class, and view model
=> [projectfirma/#1107] Make Home Page map text editable

Source/ProjectFirma.Web/Controllers/ProjectController.cs, Source/ProjectFirma.Web/Controllers/ProjectUpdateController.cs, Source/ProjectFirma.Web/Models/ProjectBudgetUpdateTest.cs, Source/ProjectFirma.Web/Models/ProjectUpdateBatch.cs, Source/ProjectFirma.Web/Models/ProjectUpdateBatchTest.cs, Source/ProjectFirma.Web/Views/Project/Detail.cshtml, Source/ProjectFirma.Web/Views/Project/DetailViewData.cs, Source/ProjectFirma.Web/Views/ProjectUpdate/BudgetsViewData.cs, Source/ProjectFirma.Web/Views/ProjectUpdate/ProjectUpdateViewData.cs, Source/ProjectFirma.Web/Views/ProjectUpdate/SiteLayout.cshtml, Source/ProjectFirma.Web/Views/Shared/ProjectControls/EditProjectViewData.cs
=> [projectfirma/#1136] Remove Budgets module for RCDs

Source/ProjectFirma.Web/Controllers/OrganizationController.cs, Source/ProjectFirma.Web/Models/Organization.cs, Source/ProjectFirma.Web/Views/Organization/Detail.cshtml, Source/ProjectFirma.Web/Views/Organization/DetailViewData.cs, Source/ProjectFirma.Web/Views/PerformanceMeasure/PerformanceMeasureChart.cshtml
Filter PMs correctly, fix redraw for charts, remove enlarge as it isn't accurate
=> [projectfirma/#1121] Show PM charts on Org pages

Source/ProjectFirma.Web/Models/Organization.cs, Source/ProjectFirma.Web/Models/ProjectFundingSourceExpenditure.DatabaseContextExtensions.cs, Source/ProjectFirma.Web/Views/Organization/ProjectsIncludingLeadImplementingGridSpec.cs
Removing the expenditure columns after all, gutting no longer used functions
https://projects.sitkatech.com/projects/projectfirma/cards/1134
=> [projectfirma/#1134] Show more project info on Org Summary page

Source/ProjectFirma.Web/Controllers/ProjectController.cs, Source/ProjectFirma.Web/Views/Project/BackwardLookingFactSheet.cshtml, Source/ProjectFirma.Web/Views/Project/ForwardLookingFactSheet.cshtml
Add setting to zoom pdf content to 90% and download as file
=> [projectfirma/#1236] Make Fact Sheets print to PDF

Source/ProjectFirma.Web/Controllers/ProjectLocationController.cs, Source/ProjectFirma.Web/Views/Shared/ProjectLocationControls/EditProjectBoundingBoxViewModel.cs
Remove fullscreen button, remove additional bounding box layer, make bounding box optional and delete if form is submitted with no coordinates
=> [projectfirma/#1261] Fact Sheets colors and maps (groan)

Source/ProjectFirma.Web/Views/ProjectCreate/EditProposalClassificationsViewModel.cs, Source/ProjectFirma.Web/Views/Shared/ProjectControls/EditProjectClassificationsForProjectViewModel.cs
* Removed validation so user can now choose a theme without adding a note
=> [projectfirma/#1334] Make comments optional on Project Classification

Source/ProjectFirma.Web/Models/FirmaPageType.cs, Source/ProjectFirma.Web/Models/Project.cs, Source/ProjectFirma.Web/Views/Project/BackwardLookingFactSheet.cshtml, Source/ProjectFirma.Web/Views/Project/BackwardLookingFactSheetViewData.cs, Source/ProjectFirma.Web/Views/Project/ForwardLookingFactSheet.cshtml, Source/ProjectFirma.Web/Views/Project/ForwardLookingFactSheetViewData.cs
-Fix no funding source identified amount so it matched Targeted Funding Chart
-Only show targeted accomplishments amounts if there are any values set
-Fix formatting on fact sheet
=> Multi-tenant fixes for expected accomplishments and funding amounts

Database/ReleaseScript/0190 - Add FundingSourceAmount.sql, Database/Tables/dbo.FundingSource.sql, Source/ProjectFirma.Web/DatabaseEntities.csdl, Source/ProjectFirma.Web/DatabaseEntities.ssdl, Source/ProjectFirma.Web/Models/Generated/FundingSource.Binding.cs, Source/ProjectFirma.Web/Views/FundingSource/Edit.cshtml, Source/ProjectFirma.Web/Views/FundingSource/EditViewModel.cs
[projectfirma/#1409] Track Funding Source Amount
* The Funding Source Amount input uses currency formatting
=> [projectfirma/#1409] Track Funding Source Amount

Source/ProjectFirma.Web/Controllers/ProjectUpdateController.cs, Source/ProjectFirma.Web/Models/Watershed.cs
[projectfirma/#1429] Add WA DNR Regions
* Change map layer from "Region" to "Regions" and "Watershed" to "Watersheds"
* Be able to delete a project update
=> [projectfirma/#1429] Add WA DNR Regions

Source/ProjectFirma.Web/Common/MultiTenantHelpers.cs, Source/ProjectFirma.Web/Models/Person.cs, Source/ProjectFirma.Web/Models/Project.cs, Source/ProjectFirma.Web/Views/Project/DetailViewData.cs, Source/ProjectFirma.Web/Views/ProjectCreate/ProjectCreateViewData.cs, Source/ProjectFirma.Web/Views/ProjectUpdate/EditProjectUpdateConfigurationViewModel.cs, Source/ProjectFirma.Web/Views/ProjectUpdate/Manage.cshtml, Source/ProjectFirma.Web/Views/ProjectUpdate/ManageViewData.cs
=> [projectfirma/#1436] Configure roles for project tracker Part 2

Source/ProjectFirma.Web/Models/NotificationType.cs
[projectfirma/#1430] Make "Project" a customizable label
* Replace Project with the field definition on the System Communications Notification Type label
=> [projectfirma/#1430] Make "Project" a customizable label

Source/ProjectFirma.Web/Views/Shared/ProjectLocationControls/ApproveGisUpload.cshtml
This may not be an active bug on the Firma side, but it's definitely a latent one.
See WADNR for background: features/1444_detailedLocations - Fixing upload bug on multi-features where we were submitting multiple form elements
=> Fixing bug where multi-features would fail to post correctly because of form element duplication

Database/ReleaseScript/0220 - Changing Entity Lead to Lead Entity in Geospatial Area Type.sql
Changing "Entity Lead" to "Lead Entity" in GeoSpatial Area Type
=> [delta/#239] Identify NTA's Lead Entities and Counties via a map

Database/ReleaseScript/0221 - Add tenant open id columns.sql
=> Fixed a mixed up client identifier

Source/ProjectFirma.Web/Models/TaxonomyBranchModelExtensions.cs, Source/ProjectFirma.Web/Views/TaxonomyBranch/IndexGridSpec.cs, Source/ProjectFirma.Web/Views/TaxonomyTrunk/IndexGridSpec.cs
Added Trunk Description to Taxonomy Trunk Index Page
Added Branch Description to Taxonomy Branch Index Page
=> Added Regional Priority code in the Taxonomy Branch index page

Source/ProjectFirma.Web/Models/IRoleExtensions.cs, Source/ProjectFirma.Web/Views/Role/DetailViewData.cs
Added an if else block to display the default definition if no custom definition is provided
=> [projectfirma/#1465] Bug: fix Role Description field definition

Source/ProjectFirma.Web/Views/FieldDefinition/FieldDefinitionGridSpec.cs
After talking with Matt, just resized the columns that already existed in grid spec
=> [projectfirma/#1543] Add definition content to the download of field definitions

Source/ProjectFirma.Web/Controllers/ProjectUpdateController.cs, Source/ProjectFirma.Web/FirmaOwinStartup.cs, Source/ProjectFirma.Web/Models/NotificationModelExtensions.cs, Source/ProjectFirma.Web/ScheduledJobs/HangfireFirmaWebAuthorizationFilter.cs, Source/ProjectFirma.Web/ScheduledJobs/ProjectUpdateReminderScheduledBackgroundJob.cs, Source/ProjectFirma.Web/ScheduledJobs/ScheduledBackgroundJobBootstrapper.cs
ctrl RG to reorganize usings while investigating bug
Bug Not Found - see https://projects.sitkatech.com/projects/projectfirma/cards/1486 for report
=> [projectfirma/#1486] Bug: Project Update notification's subject line logic doesn't handle PF subdomains

Database/ReleaseScript/0243 - Deleting More Idaho Provided Project Names From Project Firma Database.sql
****don't push to prod until tested in qa ****
=> Removes 132 Projects Idaho wished to see removed in second round of project deletion

Source/ProjectFirma.Web/Common/FirmaWebConfiguration.cs, Source/ProjectFirma.Web/Views/Shared/NavAndHeaderLayout.cshtml, Source/ProjectFirma.Web/Web.config.template
=> [delta/#288] Respond to NEP Atlas Feedback

Database/LookupTables/dbo.FieldDefinition.sql, Database/ReleaseScript/0263 - Add CanManageCustomAttributes column to TenantAttribute.sql, Database/ReleaseScript/0268 - ManageFundingSourceCustomAttributesTypeList for Idaho Soil.sql, Database/ReleaseScript/0269 - Update Default and Custom Label for Project Custom Attribute.sql, Source/ProjectFirma.Web/Controllers/ProjectController.cs, Source/ProjectFirma.Web/Models/ProjectFundingSourceExpenditureModelExtensions.DatabaseContextExtensions.cs, Source/ProjectFirma.Web/Views/FirmaViewData.cs, Source/ProjectFirma.Web/Views/FundingSourceCustomAttributeType/ManageViewData.cs, Source/ProjectFirma.Web/Views/Project/ProjectExcelSpec.cs, Source/ProjectFirma.Web/Views/ProjectCustomAttributeType/ManageViewData.cs, Source/ProjectFirmaModels/Models/FundingSourceCustomAttributeTypeRole.cs, Source/ProjectFirmaModels/Models/FundingSourceCustomAttributeValue.cs, Source/ProjectFirmaModels/Models/ProjectCustomAttributeTypeRole.cs, Source/ProjectFirmaModels/Models/ProjectCustomAttributeValue.cs, Source/ProjectFirmaModels/ProjectFirmaModels.csproj
Rework for both #1707 and #1663 are in this branch
=> [projectfirma/#1707] and [projectfirma/#1663]: rework

Source/ProjectFirma.Web/Models/PersonModelExtensions.cs
Set TenantID for anonymous user so DatabaseEntities.SaveChanges would not fail when non-logged in users sumbit a Support Request
=> [delta/#362] Bug fix for Aw Shucks when submitting Support Request as anonymous user

Source/ProjectFirma.Web/Models/ProjectFundingSourceBudgetUpdateModelExtensions.cs
bug fix: NoFundingSourceIdentifiedYet was not be…ing commited to the Project upon approval of a Project Update
=> commit NoFundingSourceIdentifiedYet to project

Source/ProjectFirma.Web/Views/ProjectUpdate/ExpectedFunding.cshtml, Source/ProjectFirma.Web/Views/ProjectUpdate/ExpectedFundingByCostType.cshtml, Source/ProjectFirma.Web/Views/ProjectUpdate/ExpectedFundingByCostTypeViewModel.cs, Source/ProjectFirma.Web/Views/ProjectUpdate/ExpectedFundingViewModel.cs, Source/ProjectFirma.Web/Views/Shared/ExpenditureAndBudgetControls/ProjectBudgetSummary.cshtml, Source/ProjectFirma.Web/Views/Shared/ExpenditureAndBudgetControls/ProjectBudgetsAnnual.cshtml, Source/ProjectFirma.Web/Views/Shared/ExpenditureAndBudgetControls/ProjectBudgetsAnnualByCostType.cshtml
Various UI changes following testing.
=> [projectfirma/#1607] Add comment to Project Budget in Update workflow rework

Source/ProjectFirma.Web/Controllers/ProjectController.cs, Source/ProjectFirma.Web/Controllers/ProjectUpdateController.cs, Source/ProjectFirma.Web/Views/Shared/ExpenditureAndBudgetControls/ProjectBudgetsAnnual.cshtml, Source/ProjectFirma.Web/Views/Shared/ExpenditureAndBudgetControls/ProjectBudgetsAnnualByCostType.cshtml, Source/ProjectFirma.Web/Views/Shared/ExpenditureAndBudgetControls/ProjectBudgetsAnnualByCostTypeViewData.cs, Source/ProjectFirma.Web/Views/Shared/ExpenditureAndBudgetControls/ProjectBudgetsAnnualViewData.cs
need to display the comment from the ProjectUpdateBatch when viewing a submitted update in the ProjectUpdate workflow view
=> 1607 rework: display comment from update batch

Source/ProjectFirma.Web/Models/FirmaPageModelExtensions.cs
A suggested partial fix so that PF doesn't completely crash when a FirmaPage is not defined, but at least puts up an on-screen error showing what FirmaPage needs to be defined.
Ideally this could be taken farther and we make a New() editor instead of just Edit(), but this is a start.
=> ProjectFirma:

Database/LookupTables/dbo.FileResourceMimeType.sql, Source/ProjectFirmaModels/Models/Generated/FileResourceMimeType.Binding.cs
Add the KMZ and KML mimetypes to the attachment relationship types
=> [projectfirma/#1785] Allow Admins to Manage Attachment Types

Source/ProjectFirma.Web/Controllers/ProjectAttachmentController.cs, Source/ProjectFirma.Web/Views/Shared/ProjectAttachment/EditProjectAttachmentsViewModel.cs, Source/ProjectFirma.Web/Views/Shared/ProjectAttachment/NewProjectAttachment.cshtml, Source/ProjectFirma.Web/Views/Shared/ProjectAttachment/NewProjectAttachmentViewModel.cs
Only allow unique display names for project attachments at the attachment type level
=> [projectfirma/#1789] Allow Users to Add/Edit Attachments

Source/ProjectFirma.Web/Controllers/FundingSourceController.cs
Adjust Budget grid on Funding Source detail page display one line per project
=> [projectfirma/#1834] Bug for Funding Source detail page

Source/ProjectFirma.Web/Views/Shared/ProjectContact/ProjectContactController.js
Fix typo that was causing multiple contacts for contact relationship types that should not allow them
=> [projectfirma/#1835] Bug: changing contact just adds new contact

Source/ProjectFirma.Api/Controllers/ProjectDto.cs
For: [delta/#363] Update NEP Atlas financial data sync
=> Updated API to include TargetedFunding in the ProjectDto

Source/ProjectFirma.Web/Controllers/ResultsController.cs, Source/ProjectFirma.Web/Views/Results/FundingStatus.cshtml
emoved legend of funding status bar chart; changed layout so chart header better aligns with rich text editor text; changed 'Org' to 'Organization' in bar chart title
=> [projectfirma/#1629] Custom Result Page Rework

Database/ReleaseScript/0307 - Add ExcludeTargetedFundingOrganizations to TenantAttribute table.sql, Database/Tables/dbo.TenantAttribute.sql, Source/ProjectFirma.Web/Controllers/ProjectController.cs, Source/ProjectFirma.Web/Models/ProjectModelExtensions.cs, Source/ProjectFirma.Web/Views/Tenant/Detail.cshtml, Source/ProjectFirma.Web/Views/Tenant/EditBasics.cshtml, Source/ProjectFirma.Web/Views/Tenant/EditBasicsViewModel.cs, Source/ProjectFirmaModels/Models/Generated/TenantAttribute.Binding.cs, Source/ProjectFirmaModels/Models/Generated/TenantAttributeConfiguration.Binding.cs
Create configuration setting to exclude targeted funders from forward lookign fact sheet header and organization section of project details page
=> [projectfirma/#1840] Exclude targeted funders with tenant config

Source/ProjectFirma.Web/Models/FundingSourceModelExtensions.cs, Source/ProjectFirma.Web/Views/FundingSource/IndexGridSpec.cs
=> [projectfirma/#1857] Add Budget information columns to Funding Program Index page

Source/ProjectFirma.Web/Views/PerformanceMeasure/DefinitionAndGuidance.cshtml
added '[project] reporting instructions' section to popup for progress measure in accomplishments section of project update. Also added link to PM detail page at the bottom of the popup
=> [projectfirma/#1594] Provide PM reporting guidance in project update

Source/ProjectFirma.Web/Controllers/ClassificationController.cs, Source/ProjectFirma.Web/Models/ClassificationModelExtensions.cs, Source/ProjectFirma.Web/Views/Classification/Detail.cshtml, Source/ProjectFirma.Web/Views/Classification/DetailViewData.cs
Visualize a project portfolio (by improving classification detail page)
=> [projectfirma/#1942] Improve classification detail page

Source/ProjectFirma.Web/Controllers/ClassificationController.cs, Source/ProjectFirma.Web/Controllers/HomeController.cs, Source/ProjectFirma.Web/Controllers/ResultsController.cs, Source/ProjectFirma.Web/Controllers/TaxonomyBranchController.cs, Source/ProjectFirma.Web/Controllers/TaxonomyLeafController.cs, Source/ProjectFirma.Web/Controllers/TaxonomyTrunkController.cs, Source/ProjectFirma.Web/Models/ProjectColorByTypeModelExtensions.cs, Source/ProjectFirma.Web/Views/Results/ProjectMap.cshtml, Source/ProjectFirma.Web/Views/Shared/ProjectLocationControls/ProjectLocationsMap.cshtml, Source/ProjectFirma.Web/Views/Shared/ProjectLocationControls/ProjectLocationsMapViewData.cs
changed Project Location Map legend title to be a field definition with (?) popup; allowed map on classification detail page to be full screen
=> [projectfirma/#1942] Project Location Map legend title field definition

Source/ProjectFirma.Web/Views/ProjectCustomGrid/ProjectCustomGridSpec.cs
=> [projectfirma/#1896] View a project's update history as a timeline

Source/ProjectFirma.Web/Views/WebServices/List.cshtml
* Only display the geospatial areas if any are present on the tenant
=> [projectfirma/#1963] Expose project web feature service

Source/ProjectFirma.Web/Views/ProjectProjectStatus/ProjectProjectStatusDetails.cshtml
* Add existing field defintions to project status details modal
=> [projectfirma/#1973] Add field definitions for Project Status fields

Source/ProjectFirma.Web/Views/Shared/ViewGoogleChart.cshtml
preventing javascript error when there is no google chart to show
=> [projectfirma/#1911] Bug Fix for Performance Measure details

Database/ReleaseScript/0362 - creating project evaluation tables.sql
* Adding default definitions for evaluation field definitions
=> [projectfirma/#1400] Evaluate a project using one or more criteria

Source/ProjectFirma.Web/Controllers/EvaluationController.cs, Source/ProjectFirma.Web/Views/Evaluation/AddProjectEvaluation.cshtml, Source/ProjectFirma.Web/Views/Evaluation/AddProjectEvaluationController.js, Source/ProjectFirma.Web/Views/Evaluation/AddProjectEvaluationViewData.cs, Source/ProjectFirmaModels/Models/ProjectSimple.cs, Source/ProjectFirmaModels/Models/ProjectStageSimple.cs, Source/ProjectFirmaModels/ProjectFirmaModels.csproj
* Additional option to filter added projects by stage
* Bug fixes with interface
=> [projectfirma/#1399] Manage project evaluations

Database/ReleaseScript/0369 - lessons learned field definition defaults.sql
* Adjust default field definitions for Tenant Config options
* Create separate defaults for TenantID 11 (PSP)
=> [projectfirma/#1962] Capture "lessons learned" for a completed project

Source/ProjectFirma.Api/Controllers/FundingSourceController.cs, Source/ProjectFirma.Api/Controllers/FundingSourceDto.cs, Source/ProjectFirma.Api/Controllers/OrganizationDto.cs, Source/ProjectFirma.Api/Controllers/OrganizationsController.cs, Source/ProjectFirma.Api/ProjectFirma.Api.csproj
added APIs to add, update and delete funding sources and organizations in PF from PS Info
=> [delta/#398] [delta/#399] [delta/#401] Org and Funding Sources API for PS Info sync

Database/ReleaseScript/0376 - add ReportCenter tables.sql, Database/Tables/dbo.ReportTemplate.sql, Source/ProjectFirmaModels/Models/Generated/ReportTemplate.Binding.cs, Source/ProjectFirmaModels/ProjectFirmaModels.csproj
* fix test for AssureNoMissingForeignKeys
=> [projectfirma/#2048] Upload Report Templates

Source/ProjectFirma.Web/ReportTemplates/Models/ReportTemplateProjectModel.cs
* Some prevention of null reference exceptions
=> [projectfirma/#2050] Run a report on selected projects

Source/ProjectFirma.Web/Controllers/ProjectCreateController.cs
* Fix bug causing basics page on create workflow with already existing project to fail due to the project type
=> [projectfirma/#1868] Create and Update an Administrative Project

Source/ProjectFirma.Api/Models/ProjectDto.cs
Display last updated date in NEP Activities grid and on detail page: Added LastUpdatedDate to the Project API to pass this date to PsInfo
=> [delta/#410] Update Project API

Database/LookupTables/dbo.FirmaPageType.sql, Database/ReleaseScript/0389 - Add FirmaPage for Release Notes.sql, Source/ProjectFirma.Web/Controllers/HomeController.cs, Source/ProjectFirma.Web/Views/Home/ReleaseNotes.cshtml, Source/ProjectFirma.Web/Views/Home/ReleaseNotesViewData.cs, Source/ProjectFirmaModels/Models/Generated/FirmaPageType.Binding.cs
* Adding new firma page
* Displaying new firma page on the release notes page
=> [projectfirma/#2083] Edit text at top of Release Notes page

Source/ProjectFirma.Web/Models/PersonModelExtensions.cs, Source/ProjectFirma.Web/Models/ProjectTimeline.cs, Source/ProjectFirma.Web/Views/Shared/ProjectTimeline/ProjectTimelineDisplay.cshtml
* Adding the contact types after the persons name on the project history timeline
=> [projectfirma/#2064] Add Contact Type to Project Status History

Source/ProjectFirma.Web/Controllers/WebServicesController.cs, Source/ProjectFirma.Web/Views/WebServices/Index.cshtml
* Allowing viewing of the Web Services page without logging in.
=> [projectfirma/#2084] View Web Services page without having to log in

Database/Tables/dbo.DocumentLibraryDocumentCategory.sql, Source/ProjectFirma.Web/Controllers/DocumentLibraryController.cs, Source/ProjectFirma.Web/Views/DocumentLibrary/EditViewModel.cs, Source/ProjectFirmaModels/Models/Generated/DatabaseEntities.Context.Binding.cs, Source/ProjectFirmaModels/Models/Generated/DocumentLibraryDocumentCategory.Binding.cs, Source/ProjectFirmaModels/Models/Generated/DocumentLibraryDocumentCategory.DatabaseContextExtensions.cs, Source/ProjectFirmaModels/Models/Generated/DocumentLibraryDocumentCategoryConfiguration.Binding.cs, Source/ProjectFirmaModels/ProjectFirmaModels.csproj
* Gen'ing and committing after recent changes
=> [#1076] manage document libraries

Database/LookupTables/dbo.DocumentCategory.sql, Source/ProjectFirma.Web/Views/DocumentLibrary/Index.cshtml, Source/ProjectFirma.Web/Views/FirmaViewData.cs
Added additional categories to the DocumentCategory lookup table script; change menu item to read 'Document Libraries'; changed wording on index page
=> [projectfirma/#1076] Manage Document Libraries: rework

Source/ProjectFirma.Web/Common/MultiTenantHelpers.cs, Source/ProjectFirma.Web/Controllers/UserController.cs
* eager loading the tenant attribute primary contact person's organization to prevent crashes
=> [projectfirma/#2147] Bug: Invite user is broken

Source/ProjectFirma.Web/Controllers/DocumentLibraryController.cs, Source/ProjectFirmaModels/Models/FileResourceData.cs, Source/ProjectFirmaModels/ProjectFirmaModels.csproj
Also ensure FileResourceInfo/Data deleted when a document library document is deleted.
=> [projectfirma/#2138] Bug Fix: Make FileResourceData an IAuditableEntity 

Source/ProjectFirma.Web/Controllers/ProjectStatusController.cs, Source/ProjectFirma.Web/Views/Evaluation/IndexViewData.cs, Source/ProjectFirma.Web/Views/FirmaViewData.cs, Source/ProjectFirma.Web/Views/FundingSourceCustomAttributeType/ManageViewData.cs, Source/ProjectFirma.Web/Views/Home/ManageHomePageImages.cshtml, Source/ProjectFirma.Web/Views/Home/ManageHomePageImagesViewData.cs, Source/ProjectFirma.Web/Views/ProjectCustomAttributeGroup/ManageViewData.cs, Source/ProjectFirma.Web/Views/ProjectCustomAttributeType/ManageViewData.cs, Source/ProjectFirma.Web/Views/ProjectStatus/ManageViewData.cs, Source/ProjectFirma.Web/Views/Tag/IndexViewData.cs, Source/ProjectFirma.Web/Views/Tenant/DetailViewData.cs
removed the word 'Manage' from all page titles (so the page titles match the menu item names); fixed pluralizing the Status Field Definition; fixed Homepage Images page to use a PageTitle
=> [projectfirma/#2139] rework

Source/ProjectFirma.Web/Controllers/ProjectFactSheetController.cs, Source/ProjectFirma.Web/Views/ProjectFactSheet/EditFactSheetLogoViewModel.cs, Source/ProjectFirma.Web/Views/Shared/DisplayDocumentLibrary.cshtml
bug fix: fix editing and deleting fact sheet logo from manage fact sheet page; if a mime type does not have an icon, just show the alt text when displaying a document library on an about page
=> [projectfirma/#2138] rework/bug fix

Source/ProjectFirma.Web/Views/Classification/Edit.cshtml, Source/ProjectFirma.Web/Views/Classification/EditViewModel.cs
* Quick fix since recent file resource table renames
=> [projectfirma/#1472] Allow admin to delete photo on classification tile

Source/ProjectFirma.Web/Controllers/OrganizationController.cs, Source/ProjectFirma.Web/Models/ProjectFundingSourceExpenditureModelExtensions.cs
changed the chart type for expenditures to be a column chart instead of an area (line) chart
=> Delta-571: changed the chart type for expenditures to be a column chart

Source/ProjectFirma.Web/Views/Shared/ExpenditureAndBudgetControls/ProjectExpendituresByCostTypeDetail.cshtml, Source/ProjectFirma.Web/Views/Shared/ViewGoogleChart.cshtml
prevent flickering of tooltip; ensure cursor style is consistent in the options menu.
PORK: fixed bug with expenditures by cost type detail display: years not sorted properly
=> Delta-571: rework and bug fix for expenditures by cost type detail display

Database/ReleaseScript/0420 - Add custom report training video.sql, Database/Tables/dbo.TrainingVideo.sql, Source/ProjectFirma.Web/Views/Home/TrainingVideo.cshtml, Source/ProjectFirmaModels/Models/Generated/TrainingVideo.Binding.cs, Source/ProjectFirmaModels/Models/Generated/TrainingVideoConfiguration.Binding.cs
* Adding youtube videos to PF training page
=> Report Center Training:

Source/ProjectFirma.Web/Views/Shared/EditorTemplates/ProjectCustomAttributes.cshtml
Use unique input/label ids for select many custom attributes to avoid collisions
=> PF-2217: Custom attributes bug

Source/ProjectFirma.Web/Controllers/ResultsController.cs, Source/ProjectFirma.Web/Views/Classification/Detail.cshtml, Source/ProjectFirma.Web/Views/GeospatialArea/Detail.cshtml, Source/ProjectFirma.Web/Views/Home/Index.cshtml, Source/ProjectFirma.Web/Views/Organization/Detail.cshtml, Source/ProjectFirma.Web/Views/Results/ProjectMap.cshtml, Source/ProjectFirma.Web/Views/Results/ProjectMapViewData.cs, Source/ProjectFirma.Web/Views/Shared/ProjectLocationControls/ProjectLocationsMap.cshtml, Source/ProjectFirma.Web/Views/TaxonomyBranch/Detail.cshtml, Source/ProjectFirma.Web/Views/TaxonomyLeaf/Detail.cshtml, Source/ProjectFirma.Web/Views/TaxonomyTrunk/Detail.cshtml
layout changes for the Project Map page. Added clustering option to remaining pages that use the ProjectLocationMap
=> PF-2206: Map Improvement Rework

Source/ProjectFirma.Web/Views/ProjectCreate/Basics.cshtml, Source/ProjectFirma.Web/Views/ProjectCreate/BasicsViewData.cs
Handle empty "planning/design start year" selector better.
=> Smarter year selection - filter to only valid options

Source/ProjectFirma.Web/Views/ProjectCreate/PerformanceMeasures.cshtml, Source/ProjectFirma.Web/Views/ProjectCreate/PerformanceMeasuresController.js, Source/ProjectFirma.Web/Views/ProjectUpdate/ReportedPerformanceMeasures.cshtml
updated variable names in Angular to match the names in the View Model (which were changed Feb 2020). Updated instructions to better match what the page does. Used project field definition instead of hard coded 'project'.
=> PF-2257: Bug fixes for Project Create Reported Performance Measures

Source/LtInfo.Common/DhtmlWrappers/DhtmlxGridHtmlHelpersTest.VerifyJavascriptForDhtmlxGrid.approved.txt
=> PF-2198 Create custom BiOp Annual Report results page

Source/ProjectFirma.Web/ProjectFirma.Web.csproj, Source/ProjectFirma.Web/Views/ProjectCreate/Basics.cshtml, Source/ProjectFirma.Web/Views/ProjectCreate/BasicsViewData.cs, Source/ProjectFirma.Web/Views/ProjectUpdate/Basics.cshtml, Source/ProjectFirma.Web/Views/ProjectUpdate/BasicsViewData.cs, Source/ProjectFirma.Web/Views/Shared/ConstrainProjectYears.js, Source/ProjectFirma.Web/Views/Shared/ProjectControls/EditProject.cshtml, Source/ProjectFirma.Web/Views/Shared/ProjectControls/EditProjectViewData.cs
Extract common javascript and apply to all relevant workflows -
project edit, update, and create
=> PF-2066 Smarter year selection

Source/ProjectFirma.Web/Controllers/ProjectUpdateController.cs
Saved necessary performance measure reporting periods to the database
before creating new project updates. This prevents unique key
violations when multiple reporting periods are created for the same
year without saving to the database in beween.
=> PF-2258 Exception on begin project update for JD

Source/ProjectFirma.Web/PartnerFinder/ProjectOrganizationMatchmaker.cs, Source/ProjectFirma.Web/Views/Organization/Detail.cshtml, Source/ProjectFirmaModels/Models/Organization.DatabaseContextExtensions.cs
- some layout changes; 
- fixed bug where organizations that were opted-out still appeared in the list of potential partner matches
=> PF-2239: rework

Source/LtInfo.Common/DbSpatial/DbSpatialHelper.cs
Hotfix for production crash on GDB upload
=> ProjectFirma: Fixing holes in 4326 not being set correctly during GDB upload

Source/ProjectFirma.Web/Content/combo-tree/comboTreePlugin.js, Source/ProjectFirma.Web/Views/Organization/EditProfileTaxonomy.cshtml, Source/ProjectFirma.Web/Views/Shared/EditorTemplates/SitkaLeftRightListbox.cshtml
adjusted styling of EditProfileTaxonomy and SitkaLeftRightListbox so that the editors look more similar
=> PF-2260: Rework: fixed styling

Source/LtInfo.Common/DhtmlWrappers/DhtmlxGridHtmlHelpersTest.VerifyJavascriptForDhtmlxGrid.approved.txt
=> PF-2243 Project Finder Page

Source/LtInfo.Common/ImageHelper.cs
added helper method to add rotation to an image when redrawing it in ScaleImage()
=> PF-2305: Photo orientation bug fix

Source/ProjectFirma.Web/Views/ProjectStewardOrganization/Index.cshtml
=> PF-2302 Improve Org Detail tab structure

Source/ProjectFirma.Web/Views/Shared/GoogleChartPopup.cshtml, Source/ProjectFirma.Web/Views/Shared/GoogleCharts.js, Source/ProjectFirma.Web/Views/Shared/ViewGoogleChart.cshtml
* make the chart editor only allow one open modal at a time
=> PF-2269 Detailed Location: GIS upload functionality not working

Source/ProjectFirma.Web/Views/TechnicalAssistanceRequest/TechnicalAssistanceReportGridSpec.cs
=> PF-2340 Add Last Updated column to Idaho's Technical Assistance Report

Source/LtInfo.Common/SitkaGeometryDisplayErrorException.cs
* edit exception message for developers
=> PF-1219 Better error handling on GIS upload

Source/ProjectFirma.Web/Controllers/ProjectUpdateController.cs
Bug fix: PM reported accomplishments pre-population logic was erroneously including exempt years
=> PF-2357: Bug: PM pre-pop adds year records for excluded years

Source/ProjectFirma.Web/Models/NotificationProjectModelExtensions.cs
fixed one bad copy/paste issue (needed to add new contacts to emailsToReplyTo not emailsToSendTo); updated variable name to contactsWhoCanManageProject
=> PF-2371: bug fix

Source/ProjectFirma.Web/Common/FirmaWebConfiguration.cs, Source/ProjectFirma.Web/Common/MultiTenantHelpers.cs, Source/ProjectFirma.Web/Common/SitkaRoute.cs, Source/ProjectFirma.Web/Global.asax.cs, Source/ProjectFirma.Web/Web.config.template
adding new configs to handle reclamation offsite hosting and no SSL and allow setting a default tenant
=> PF-2377 On-site deployment work: auth, standing up mock env

Database/ReleaseScript/0484 - Copy GeospatialArea from RCD Prokect Tracker to NCRP Project Tracker.sql, Source/ProjectFirma.Web/Views/MapLayer/Index.cshtml
Pork: make the 'Add a new External Reference Layer' button clickable on the Map Layers page.
=> PF-2403: copy the GeospatialAreas from RCD Project Tracker to the NCRP Project Tracker

Source/ProjectFirma.Web/Controllers/UserController.cs, Source/ProjectFirma.Web/Models/NotificationProjectModelExtensions.cs
added tenant logo to project update/create approved/returned emails and invite user email.
=> PF-1146: added tenant logo to emails

Source/ProjectFirma.Web/Web.config.template
updating web.config template to include updates to binding redirects
=> PF-2101 Tech debt: Update libraries - NuGet
