sitkatech/projectfirma

Source/ProjectFirma.Web/Models/Organization.cs
Source/ProjectFirma.Web/Views/Organization/DetailViewData.cs
Source/ProjectFirma.Web/Views/Organization/ProjectsIncludingLeadImplementingGridSpec.cs

Add column header spanning all reported expenditure columns in org-project grid; updated reported expenditures to display all reported values, regardless of which organization the reported funding source belongs to
https://projects.sitkatech.com/projects/projectfirma/cards/1134

[projectfirma/#1134] Show more project info on Org Summary page

---

Source/ProjectFirma.Web/Models/Organization.cs
Source/ProjectFirma.Web/Views/Organization/Detail.cshtml

Wait to draw PM charts until results tab has been clicked
https://projects.sitkatech.com/projects/projectfirma/cards/1121
+ Make charts switch from two to one column at medium screenwidth
+ Wait to draw chart until tab has been clicked to fix dumb display errors once and for all

[projectfirma/#1121] Show PM charts on Org pages

---

Source/ProjectFirma.Web/Controllers/ResultsController.cs

Should never see empty charts - filter PMs again by the projects, which are already filtered by the org

[projectfirma/#1251] Accomplishments Dashboard go-live punchlist

---

Source/ProjectFirma.Web/Models/PerformanceMeasureActualSubcategoryOptionSimple.cs

Bug fix: If the database is missing a PerformanceMeasureSubcategoryOp…tionID for a PerformanceMeasureActualSubcategoryOption, it will break front-end validation. Added a check to the constructors of PerformanceMeasureSubcategoryOptionSimple to correctly populate that ID (a nullable int) as null in this case.

Reported Performance Measure Validation Fix

---

Source/ProjectFirma.Web/Models/Project.cs
Source/ProjectFirma.Web/Views/Project/BackwardLookingFactSheet.cshtml
Source/ProjectFirma.Web/Views/Project/BackwardLookingFactSheetViewData.cs
Source/ProjectFirma.Web/Views/Project/ForwardLookingFactSheet.cshtml
Source/ProjectFirma.Web/Views/Project/ForwardLookingFactSheetViewData.cs

[projectfirma/#1335] Make funding sources more explicit on Fact Sheets
* Added Secured Funding, Unsecured Funding, and No Funding Source Identified to the Project Fact Sheet on the ForwardLookingFactSheet and on the BackwardLookingFactsheet

[projectfirma/#1335] Make funding sources more explicit on Fact Sheets

---

Source/ProjectFirma.Web/Models/ProjectCreateSection.cs
Source/ProjectFirma.Web/Models/ProjectUpdateSection.cs

[projectfirma/#1237] Set name of "Watersheds"
* Project Create wizard uses the plural label (e.g. “Regions”)
* Project Update wizard uses the plural label (e.g. “Regions”)

[projectfirma/#1237] Set name of "Watersheds"

---

Source/LtInfo.Common/GdalOgr/OgrInfoCommandLineRunner.cs
Source/LtInfo.Common/ProcessUtility.cs
Source/ProjectFirma.Web/Models/BoundingBox.cs
Source/ProjectFirma.Web/Models/LayerGeoJson.cs

- Multiple bizarre errors in GDAL handling causing crashes on GDAL 2.3.1, but not on GDAL 1.11.1.
- First error: Not specifying the GDAL_DATA command line argument correctly in all places
- Second error: When re-serializing the GeoJSON, we were serializing its CONTAINER object as well as the actual underlying GeoJSON. GDAL 1.11.1 was apparently tolerant of this, but GDAL 2.x is not.
- Adding logging to command line runners for all process, so we can see command line arguments.
- This work ported from WADNR/features/1444_detailedLocations

Fixing errors with GDAL causing unnecessary version sensitivity on GDAL uploads

---

Source/ProjectFirma.Web/Controllers/FundingSourceController.cs
Source/ProjectFirma.Web/Views/FundingSource/IndexGridSpec.cs

"This Funding Source is associated with {n} Projects. Deleting the Funding Source will delete all associated expenditure records. Are you sure you wish to delete Funding Source {funding source name}?"
and took out the check to see if they can delete the funding source
made the trashcan icon blue by setting the deletePossibleForObject parameter true in gridspec

Updated deletion to have the message

---

Source/ProjectFirma.Web/Views/ProjectUpdate/ExpendituresValidationResult.cs

Reverted change from revision 49c65ab30a8fc17b768a6a76d62110da4d7b646b on 6/6/2019. This code is called from the ProjectCreate as well as ProjectUpdate workflow. In ProjectUpdate, the projectFundingSourceExpenditures have been saved to the database by the time this is called. In the ProjectCreate workflow, the projectFundingSourceExpenditures have not been saved yet, so need to use x.FundingSourceID because will x.FundingSource will be null in ProjectCreate.

Bug Fix for saving Reported Expenditures in Project Create workflow

---

Database/ReleaseScript/0271 - Add unqiue constraints to ProjectCustomAttribute and FundingSourceCustomAttribute.sql
Source/ProjectFirma.Web/Controllers/FundingSourceCustomAttributesController.cs
Source/ProjectFirma.Web/Controllers/ProjectCustomAttributesController.cs

bug fix: editor modals for custom attributes should only show types that user has permission to edit. Added constraints to the database to prevent duplicate rows that break the UI.

Bug fix for editing custom attributes as non-admin user

---

Source/ProjectFirma.Web/Views/FundingSourceCustomAttributeType/Detail.cshtml
Source/ProjectFirma.Web/Views/FundingSourceCustomAttributeType/Edit.cshtml
Source/ProjectFirma.Web/Views/FundingSourceCustomAttributeType/FundingSourceCustomAttributeTypeGridSpec.cs

Removed concept of Editable By for Funding Source Custom Attibutes from the UI (left the database schema intact incase we want to have the Editable By for Funding Source Custom Attributes in the future (currently have it for Project Custom Attributes)

Funding Source Custom Attributes no long have an Editable By field in the UI

---

Source/ProjectFirma.Web/Content/angular/ng-currency.js
Source/ProjectFirma.Web/Views/ProjectCreate/ExpectedFunding.cshtml
Source/ProjectFirma.Web/Views/ProjectFundingSourceBudget/EditProjectFundingSourceBudget.cshtml
Source/ProjectFirma.Web/Views/ProjectUpdate/ExpectedFunding.cshtml

created a directive to allow negative values for currency. Use it for all NoFundingSourceIdentifiedYet input fields.  This directive is almost a copy of ngCurrency, but checks for any "-" in the string, or if the values is surrounded by parentheses (e.g. "($100,000)" ) to indicate a negative value.

Allow negative currency input for NoFundingSourceIdentifiedYet 

---

Database/ReleaseScript/0305 - adding kmz and kml Attachment Relationship Types to Documents for all tenants.sql

Adding KMZ and KML as default file types for the Documents attachment relationship type

[projectfirma/#1785] Allow Admins to Manage Attachment Types

---

Source/ProjectFirma.Web/Models/ProjectModelExtensions.cs
Source/ProjectFirma.Web/Views/Home/FeaturedProjects.cshtml

Added Lead Implementer to features projects on home page. Also increased the height of the carousel so that "view more" shows up. Did not check all Tenants, but this works for PSP.
Also fixed potential bug with Funding Status custom results page for AA: was not using the IsPrimaryContact to find the organization relationship type for 'owner organization' and should have been.

[projectfirma/#1659] Bug fix: add lead implementer to featured projects

---

Source/ProjectFirma.Web/Views/ProjectCustomGrid/ProjectCustomGridSpec.cs

* Don't display the status column if the user doesnt have edit permissions
* Don't display the status of a project if the user doesn't have permissions to edit that project

[projectfirma/#1896] View a project's update history as a timeline

---

Source/ProjectFirma.Web/Views/Shared/ProjectControls/DisplayProjectCustomAttributes.cshtml

Ensure custom attributes displayed on detail page should be viewable by the user's role (cannot just loop through all ProjectCustomAttributeTypes in a ProjectCustomAttributeGroup, but need to ensure the type is present in the list for which the permissions were checked)

[projectfirma/#1990] Custom Attributes viewable by public: rework for detail page

---

Source/ProjectFirma.Web/Common/LabelForExtensions.cs

* Moving the help icon out of the label
* Add wrapping element to the HelpIconWithLabel Display Style for the LabelWithFieldDefinitionForImpl method
* Adjusting the inline style for the label to "display:inline;" to format the help icon before the label text appropriately

[projectfirma/#2047] Bug: Focus issue on fields with Help text

---

Source/ProjectFirma.Api/Models/ProjectDto.cs

Add FundingSourceIDs to ProjectDto for all funding sources use in a project's budget or expenditures, so PS Info can know which (if any) NEP Awardee is associated with the project

[delta/#435] Add FundingSourceIDs to ProjectDto

---

Source/ProjectFirma.Api/Controllers/ProjectsController.cs

Update API to only return projects if the funding source has secured funding > $0 or expenditures > $0

[delta/#419] Update API ListNTAsForFundingSources

---

Database/ReleaseScript/0403 - Insert ProjectNoFundingSourceIdentified rows for simple budget varies by year.sql
Database/Tables/dbo.Project.sql
Database/Tables/dbo.ProjectUpdate.sql
Source/ProjectFirma.Web/Controllers/ProjectController.cs
Source/ProjectFirma.Web/Controllers/ProjectUpdateController.cs
Source/ProjectFirma.Web/Models/ProjectFundingSourceBudgetUpdateModelExtensions.cs
Source/ProjectFirma.Web/Models/ProjectUpdateBatchModelExtensions.cs
Source/ProjectFirma.Web/Views/ProjectCreate/ExpectedFundingByCostTypeViewModel.cs
Source/ProjectFirma.Web/Views/ProjectCreate/ExpectedFundingViewModel.cs
Source/ProjectFirma.Web/Views/ProjectFundingSourceBudget/EditProjectFundingSourceBudgetByCostTypeViewModel.cs
Source/ProjectFirma.Web/Views/ProjectFundingSourceBudget/EditProjectFundingSourceBudgetViewModel.cs
Source/ProjectFirma.Web/Views/ProjectUpdate/ExpectedFundingByCostTypeViewModel.cs
Source/ProjectFirma.Web/Views/ProjectUpdate/ExpectedFundingViewModel.cs
Source/ProjectFirmaModels/Models/Generated/Project.Binding.cs
Source/ProjectFirmaModels/Models/Generated/ProjectConfiguration.Binding.cs
Source/ProjectFirmaModels/Models/Generated/ProjectUpdate.Binding.cs
Source/ProjectFirmaModels/Models/Generated/ProjectUpdateConfiguration.Binding.cs
Source/ProjectFirmaModels/Models/Project.cs
Source/ProjectFirmaModels/Models/ProjectBudgetFinancialsForExcel.cs
Source/ProjectFirmaModels/Models/ProjectUpdate.cs

dropped column NoFundingSourceIdentifiedYet from Project and ProjectUpdate; migrated existing data to ProjectNoFundingSourceIdentified and ProjectNoFundingSourceIdentifiedUpdate tables; All projects save to the tables, regardless of funding type (varies by year and same each year) and tenant's budget type (annual by cost type or simple budget)

[projectfirma/#2129] dropped column NoFundingSourceIdentifiedYet

---

Source/ProjectFirma.Web/Views/Project/Detail.cshtml
Source/ProjectFirma.Web/Views/Project/DetailViewData.cs
Source/ProjectFirma.Web/Views/Project/PendingGridSpec.cs
Source/ProjectFirma.Web/Views/Project/ProposalsGridSpec.cs

Prevent normal user from editing after submitting proposal or pending project.
Give the normal users access to a "withdraw this proposal" option from the detail page if they previously had access to the create project workflow for that proposal/project.

[projectfirma/#1142] Prevent user from editing after submitting

---

Source/ProjectFirma.Web/Controllers/OrganizationController.cs
Source/ProjectFirma.Web/Views/FieldDefinition/EditViewModel.cs
Source/ProjectFirma.Web/Views/Organization/Edit.cshtml
Source/ProjectFirma.Web/Views/Organization/EditViewData.cs
Source/ProjectFirma.Web/Views/Organization/EditViewModel.cs

revisiting and reworking: 
removed the Sync with Keystone On Save checkbox, and added a button that gets the short name and URL from keystone and replaces the values in the editor. User must save the editor to save the changes to the PF Database; 
Also pork: prevent crashes on the sitka admin field definition editor by making the Default Definition required

[projectfirma/#1250] Better syncing of Organization info with Keystone

---

Source/ProjectFirma.Web/Views/ProjectCreate/BasicsViewModel.cs
Source/ProjectFirma.Web/Views/Shared/ProjectContact/EditContacts.cshtml
Source/ProjectFirma.Web/Views/Shared/ProjectOrganization/EditOrganizations.cshtml

When saving the basics section of the project create workflow for the first time, save the lead implementor and primary contact that is currently defaulted on the Organization section of Contacts section, respectively. Previous, the defaults were selected, but not saved, so the Organization and Contacts pages appeared complete when they were not. Also cleaned up the instructions text and removed the growl message about the primary contact from the Organziation page

[projectfirma/#2131] Bugs with proposal and pending project workflows

---

Source/ProjectFirma.Web/Views/DocumentLibrary/Edit.cshtml

make the Pages selectpicker always a 'dropup' so users don't have to scroll in the modal to see the options

[projectfirma/#1076] rework: make Pages selectpicker always a 'dropup'

---

Source/ProjectFirma.Web/Models/FieldDefinitionModelExtensions.cs
Source/ProjectFirma.Web/Views/Shared/ProjectOrganization/EditOrganizations.cshtml

Fixed typo in Edit Organizations instructions. 
Attempting to fix issue where we display the wrong field definition label for some tenants (e.g.: project update shows Near Term Action Custom Attributes for John Day)

[projectfirma/#2131] Rework

---

Source/ProjectFirma.Web/Common/FirmaValidationMessages.cs

Fix the validation messages so they use the Field Definitions for the correct tenant: turned the static readonly properties into static methods so the messages will be evaluated per tenant (not just fix tenant to load the application wins and has their field definition used in the readonly message)

[projectfirma/#2131] Fix the validation messages

---

Source/ProjectFirma.Web/Common/LabelForExtensions.cs
Source/ProjectFirma.Web/Views/DocumentLibrary/EditDocument.cshtml
Source/ProjectFirma.Web/Views/DocumentLibrary/NewDocument.cshtml
Source/ProjectFirma.Web/Views/FundingSourceCustomAttributeType/Edit.cshtml
Source/ProjectFirma.Web/Views/ProjectCustomAttributeType/Edit.cshtml
Source/ProjectFirma.Web/Views/ProjectFactSheet/EditFactsheetLogo.cshtml

@Html.LabelFor was not respecting tenant custom field definition labels. Added overload methods for LabelFor that should be used when using FieldDefinitionDisplay on the property in the ViewModel/ViewData class

[projectfirma/#2136] Bug fix: LabelFor() and FieldDefinitionDisplay 

---

Database/Objects/Views/dbo.vProjectDetail.sql

[Related bug card
](https://sitkatech.atlassian.net/browse/DELTA-523)
It appears as though the logic for the primary contact person was being set in conjunction with the organization's primary contact person. I believe it should be pulled directly from the project.

[delta/523] Show primary contact information in full project list

---

Source/ProjectFirma.Web/Controllers/FileResourceController.cs

change xls/xlsx file resource download method to prevent extra '.xlsx' from being appended to file name. Now uses FileResourceResult instead of ExcelResult.

[projectfirma/#2138] Pork-y Bug Fix: prevent appending '.xlsx'

---

Source/ProjectFirma.Web/Views/ProjectUpdate/BasicsValidationResult.cs

bug fix: found more validation messages that were static strings and used Field Definitions. Changes these to static messages so they would be evaluated with the current tenant's field definition each time, instead of just the first time the application is loaded (which made all tenant's get the first loaded tenant's field definitions)

PF-1805: Bug Fix: ensure tenant's field definition properly displayed in validation messages

---

Source/ProjectFirma.Web/Controllers/ProjectController.cs
Source/ProjectFirma.Web/Controllers/ProjectCreateController.cs
Source/ProjectFirma.Web/Controllers/ProjectUpdateController.cs
Source/ProjectFirma.Web/Controllers/UserController.cs
Source/ProjectFirma.Web/Models/OrganizationModelExtensions.cs
Source/ProjectFirma.Web/Models/PersonModelExtensions.cs
Source/ProjectFirma.Web/Security/UserViewFeature.cs
Source/ProjectFirma.Web/Views/Organization/Detail.cshtml
Source/ProjectFirma.Web/Views/Organization/IndexGridSpec.cs
Source/ProjectFirma.Web/Views/Project/PendingGridSpec.cs
Source/ProjectFirma.Web/Views/Project/ProjectNotificationGridSpec.cs
Source/ProjectFirma.Web/Views/Project/ProposalsGridSpec.cs
Source/ProjectFirma.Web/Views/ProjectCustomGrid/ProjectCustomGridSpec.cs
Source/ProjectFirma.Web/Views/ProjectStewardOrganization/IndexGridSpec.cs
Source/ProjectFirma.Web/Views/ProjectUpdate/MyProjectsViewData.cs
Source/ProjectFirma.Web/Views/ProjectUpdate/PeopleReceivingReminderGridSpec.cs
Source/ProjectFirma.Web/Views/ProjectUpdate/ProjectUpdateStatusGridSpec.cs
Source/ProjectFirma.Web/Views/Shared/AuditLogsGridSpec.cs

moved permission check for UserViewFeature to the PersonModelExtensions to ensure it is always checked when attempting to display a Person's detail url (there were several places the url was displayed but normal users would get an error if they clicked it). Added another method to UserViewFeature which is called in the ProjectCustomGridSpec when we only have a PersonID, and no Person model, but need to check a user's permission to view a detail page of a primary contact.

PF-2197: prevent normal user clicking other users' detail page hyperlink

---

Source/ProjectFirma.Api/Models/ProjectDto.cs
Source/ProjectFirma.Web/Models/ProjectModelExtensions.cs
Source/ProjectFirmaModels/Models/Project.cs

the ProjectDto needs an IsActive field. Move the IsActiveProject and similar methods into the Project.cs call in ProjectFirmaModels instead of having them in the ProjectModelExtensions.cs class in ProjectFirma.Web so the API can access the method.

delta-547: Move IsActiveProject from model extensions to model

---

Source/ProjectFirma.Web/Controllers/OrganizationController.cs
Source/ProjectFirma.Web/FirmaOwinStartup.cs
Source/ProjectFirma.Web/Models/MatchmakerTaxonomyTier.cs
Source/ProjectFirma.Web/Models/OrganizationModelExtensions.cs
Source/ProjectFirma.Web/PartnerFinder/ProjectOrganizationMatchmaker.cs
Source/ProjectFirma.Web/Views/Organization/ApproveUploadGisViewData.cs
Source/ProjectFirma.Web/Views/Organization/Detail.cshtml
Source/ProjectFirma.Web/Views/Organization/DetailViewData.cs
Source/ProjectFirma.Web/Views/Organization/EditBoundaryViewData.cs
Source/ProjectFirma.Web/Views/Results/AccomplishmentsDashboardViewData.cs

reload detail page on the Profile tab when returning from saving the taxonomy selector modal; updated layout of read only display; ensure taxonomy names are hyperlinks; removed fake term of partner finder algorithm.

PF-2234 rework

---

Source/ProjectFirma.Web/Common/FirmaValidationMessages.cs
Source/ProjectFirma.Web/Views/ProjectCreate/Basics.cshtml
Source/ProjectFirma.Web/Views/ProjectCreate/BasicsViewData.cs
Source/ProjectFirma.Web/Views/ProjectCreate/PerformanceMeasures.cshtml
Source/ProjectFirma.Web/Views/ProjectCreate/PerformanceMeasuresViewModel.cs
Source/ProjectFirma.Web/Views/ProjectUpdate/ReportedPerformanceMeasures.cshtml
Source/ProjectFirma.Web/Views/ProjectUpdate/ReportedPerformanceMeasuresViewModel.cs

- updated instructions; 
- added validation for length of Explanation for exempt years; 
- updated Project Create validation to require only one actual PM per non-exempt year (not one actual for each PM per year); 
- fixed bug with Project Create where the drop down for Completion Year would have a value auto selected when it should show Choose One

PF-2257: rework: 

---

Source/ProjectFirma.Web/Controllers/ProjectCreateController.cs
Source/ProjectFirma.Web/Controllers/ProjectUpdateController.cs
Source/ProjectFirma.Web/Models/ProjectExemptReportingYearUpdateSimple.cs
Source/ProjectFirma.Web/Views/ProjectCreate/PerformanceMeasuresViewModel.cs
Source/ProjectFirma.Web/Views/ProjectUpdate/ReportedPerformanceMeasures.cshtml
Source/ProjectFirma.Web/Views/ProjectUpdate/ReportedPerformanceMeasuresViewModel.cs

- changed validation to check if Explanation is within allowed length regardless of whether or not years are checked; 
- made sure the except years area is expanded on re-load if the Explanation exceeds max; 
- fixed bug with exempt years of Reported PMs of Project Update where the calendar year would not display next to the checkboxes

PF-2257: rework and bug fixes

---

Source/ProjectFirma.Web/Controllers/TaxonomyBranchController.cs
Source/ProjectFirma.Web/Controllers/TaxonomyLeafController.cs
Source/ProjectFirma.Web/Views/Shared/SortOrder/EditSortOrderInGroup.cshtml
Source/ProjectFirma.Web/Views/TaxonomyBranch/EditViewModel.cs
Source/ProjectFirma.Web/Views/TaxonomyBranch/Index.cshtml
Source/ProjectFirma.Web/Views/TaxonomyBranch/IndexViewData.cs
Source/ProjectFirma.Web/Views/TaxonomyLeaf/EditViewModel.cs
Source/ProjectFirma.Web/Views/TaxonomyLeaf/Index.cshtml
Source/ProjectFirma.Web/Views/TaxonomyLeaf/IndexViewData.cs
Source/ProjectFirmaModels/Models/TaxonomyBranch.cs
Source/ProjectFirmaModels/Models/TaxonomyTrunk.cs

- re-do the ui/ux of EditSortOrderInGroup;
- allow users to set the sort order of taxonomy branches and leafs, regardless of the tenant's taxonomy level;

PF-2250: Control sort order of Taxonomy Branches and Leaves

---

Source/ProjectFirma.Web/Controllers/ProjectCustomAttributeTypeController.cs
Source/ProjectFirma.Web/Views/Shared/SortOrder/EditSortOrderInGroup.cshtml

- changed alphabetize function to use localeCompare (numeric = true) so numbers within names are sorted like numbers;
- minor rework of layout for EditSortOrderInGroup;
- sort custom attribute groups by name for the sort editor for custom attribute types;

PF-2250: rework of UI and change to Reset to Alphabetical ordering

---

Source/ProjectFirma.Web/Controllers/ProjectUpdateController.cs

Make sure start calendar year from existing reporting periods
is always less than or equal to the current calendar year.

PF-2258 Exception on begin project update for JD

---

Source/ProjectFirma.Web/Controllers/OrganizationController.cs

Fixing crash when Organization has no projects. Revealed when bots hit these Organizations. Spoke with Shannon, she agrees no special behavior is needed when there are no Project Locations on the map.

ProjectFirma: Bug with crash on clustering of Projects on Org page

---

Source/ProjectFirma.Web/Views/Organization/Detail.cshtml

made the Profile tab visible if the Matchmaker is enabled for a tenant (even if user does not have edit permissions for the Profile)

PF-2256: made the Profile tab visible if the Matchmaker is enabled for a tenant

---

Database/LookupTables/dbo.FieldDefinition.sql
Source/ProjectFirma.Web/Controllers/FieldDefinitionController.cs
Source/ProjectFirma.Web/Views/FieldDefinition/Edit.cshtml
Source/ProjectFirma.Web/Views/FieldDefinition/EditViewModel.cs

- added comment in sql script to remind developers to add the Default Definition;
- added 'not defined' as a default in the code if it is null when trying to edit the Field Definition; 
- for Admins, made sure the editor would still work if the FieldDefinitionDetault does not exist for a FieldDefinition

PF-2276: Safe gaurding against null FieldDefinitionDefault

---

Source/ProjectFirma.Web/Controllers/AssessmentController.cs
Source/ProjectFirma.Web/Controllers/ClassificationController.cs
Source/ProjectFirma.Web/Controllers/FundingSourceController.cs
Source/ProjectFirma.Web/Controllers/GeospatialAreaController.cs
Source/ProjectFirma.Web/Controllers/HomeController.cs
Source/ProjectFirma.Web/Controllers/OrganizationController.cs
Source/ProjectFirma.Web/Controllers/ProjectController.cs
Source/ProjectFirma.Web/Controllers/ProjectCustomGridController.cs
Source/ProjectFirma.Web/Controllers/ResultsController.cs
Source/ProjectFirma.Web/Controllers/TagController.cs
Source/ProjectFirma.Web/Controllers/TaxonomyBranchController.cs
Source/ProjectFirma.Web/Controllers/TaxonomyLeafController.cs
Source/ProjectFirma.Web/Controllers/TaxonomyTrunkController.cs
Source/ProjectFirma.Web/Models/ClassificationModelExtensions.cs
Source/ProjectFirma.Web/Models/FirmaSessionModelExtensions.cs
Source/ProjectFirma.Web/Models/FundingSourceModelExtensions.cs
Source/ProjectFirma.Web/Models/GeospatialAreaModelExtensions.cs
Source/ProjectFirma.Web/Models/OrganizationModelExtensions.cs
Source/ProjectFirma.Web/Models/PerformanceMeasureModelExtensions.cs
Source/ProjectFirma.Web/Models/PersonModelExtensions.cs
Source/ProjectFirma.Web/Models/TagModelExtensions.cs
Source/ProjectFirma.Web/Models/TaxonomyBranchModelExtensions.cs
Source/ProjectFirma.Web/Models/TaxonomyLeafModelExtensions.cs
Source/ProjectFirma.Web/Models/TaxonomyTrunkModelExtensions.cs
Source/ProjectFirma.Web/Views/FundingSource/IndexGridSpec.cs
Source/ProjectFirma.Web/Views/Organization/OrganizationDetailViewData.cs
Source/ProjectFirma.Web/Views/Organization/OrganizationIndexGridSpec.cs
Source/ProjectFirma.Web/Views/ProjectStewardOrganization/IndexGridSpec.cs
Source/ProjectFirma.Web/Views/TaxonomyBranch/IndexGridSpec.cs
Source/ProjectFirma.Web/Views/TaxonomyTrunk/IndexGridSpec.cs

Hey Stewart!
As part of resolving acceptance tests for PF-2302, I noticed a potential bug related to the "Show proposals to public" tenant configuration option. Doing some debugging I found that when running the `PersonModelExtension.CanViewProposals()` extension method, it would return false if the Person was null. 
There were a lot of places in the code that were calling `currentFirmaSession.Person.CanViewProposals()`, which when run for an anonymous user, the `Person` would be null and return false regardless of whether or not the "Show proposals to public" tenant config option is enabled.
__I think__ what is committed here is an appropriate fix, but I definitely want to run it by you for any feedback or any gotcha's that I might have missed!

Fix to firma session

---

Source/ProjectFirma.Web/Models/ProjectUpdateBatchModelExtensions.cs
Source/ProjectFirma.Web/Views/ProjectUpdate/PerformanceMeasuresValidationResult.cs

we were grouping by PerformanceMeasureID, but then limiting the list of PerformanceMeasureActualUpdates to look at to just the one matching the first PerformanceMeasureActualUpdateID in the group. This resulted in odd behavior because sometimes the 'first' row would be one with missing data and the validation would fire, and sometimes not.

PF-2364: fixed bugs with Reported PM validation

---

Database/ReleaseScript/0470 - Rename ReportingYearStartDate to FiscalYearStartDate on Tenant table and update FieldDefinitionDefault.sql
Source/ProjectFirma.Web/Common/FirmaDateUtilities.cs
Source/ProjectFirma.Web/Common/MultiTenantHelpers.cs
Source/ProjectFirma.Web/Controllers/ProjectUpdateController.cs
Source/ProjectFirma.Web/Views/ProjectUpdate/MyProjectsViewData.cs
Source/ProjectFirma.Web/Views/ProjectUpdate/ProjectUpdateStatusGridSpec.cs

- update default definitions of Kick-off and Close-out dates
- update growl message when saving changes to project update configuration
- updated logic for ProjectUpdateStatusGridSpec so the "Reporting Period Update Status" column will say "Not Started" if there is an approved update but that approval did not occur in the current reporting period window.

PF-2149: rework

---

Source/ProjectFirma.Web/Controllers/ProjectUpdateController.cs
Source/ProjectFirma.Web/Models/FieldDefinitionModelExtensions.cs
Source/ProjectFirma.Web/Models/ProjectModelExtensions.cs
Source/ProjectFirma.Web/ScheduledJobs/ProjectUpdateNotificationHelper.cs
Source/ProjectFirma.Web/ScheduledJobs/ProjectUpdateReminderScheduledBackgroundJob.cs
Source/ProjectFirma.Web/Views/ProjectUpdate/EditProjectUpdateConfiguration.cshtml
Source/ProjectFirma.Web/Views/ProjectUpdate/MyProjectsViewData.cs

- added field definition methods to use for background job (when we cannot get the Tenant from the request URL);
- bug fixes for the 'My Projects requiring an update' and 'my recently submitted projects' grid

PF-2149: Project Update Configuration rework/bug fixes

---

Source/ProjectFirma.Web/Models/ProjectModelExtensions.cs
Source/ProjectFirma.Web/Views/ProjectUpdate/EditProjectUpdateConfiguration.cshtml
Source/ProjectFirma.Web/Views/ProjectUpdate/MyProjectsViewData.cs
Source/ProjectFirma.Web/Views/ProjectUpdate/ProjectUpdateStatusGridSpec.cs

- 'my projects requiring an update' grid should show all not submitted and not approved (after the last reporting period start date) project updates. 
- Fixed edge case of date comparison (should be using date only, not time). 
- Minor text changes.

PF-2149: rework/bug fixes

---

Source/ProjectFirma.Web/Models/NotificationProjectModelExtensions.cs
Source/ProjectFirmaModels/Models/Project.cs

Updated NotificationProjectModelExtensions so contacts who can manage a project are treated the same was as a primary contact (receive the same emails and are included in emails to reply to for the same emails)

PF-2371: Contacts Receive Project Notification Emails

---

Source/ProjectFirma.Web/Common/FirmaWebConfiguration.cs
Source/ProjectFirma.Web/Global.asax.cs
Source/ProjectFirma.Web/Views/Shared/NavAndHeaderLayout.cshtml
Source/ProjectFirma.Web/Web.config.template

Don't show the NCRP logo in the tenant switcher.

PF-2447: moved magic strings for url, username, and password to the web config

---

Source/ProjectFirma.Web/Views/Organization/Detail.cshtml
Source/ProjectFirma.Web/Views/Organization/OrganizationDetailViewData.cs

If an organization has no funding sources, hide the related funding source panels from Overview and Expenditures tabs

PF-2438: Conditionally Hide Funding Sources on Organization Detail page

---

Source/ProjectFirma.Web/Views/Results/AccomplishmentsDashboard.cshtml

Change the view of the Accomplishments Dashboard so that the “Accomplishments” tab is automatically opened when the page loads

show Accomplishments tab when Dashboard loads

---

Source/ProjectFirma.Web/Controllers/OrganizationController.cs

do not allow deleting an organization if it is related to Projects, Funding Sources, or any active users (updated text of delete confirmation modal to make this clear). If it is only associated with inactive users, change the user's organization to the "unknown organization" to prevent cascading deleting of projects associated with that user when the organization is deleted.

PF-2486: Prevent cascading deletes of projects & users when an org is deleted

---

Source/ProjectFirma.Web/Controllers/OrganizationController.cs
Source/ProjectFirma.Web/Views/Organization/Detail.cshtml
Source/ProjectFirma.Web/Views/Organization/OrganizationIndexGridSpec.cs

Add "Is Active?" field to Org Detail Basics. Update logic of "# of User" column of index grid to only count active users. Updated logic of delete to prevent deleting an org when it is related to non-approved project update batches. Added sentence to confirm delete dialog explaining the relationship to the projects/project updates/funding sources must be removed before the org can be deleted.

PF-2486: rework

---

Source/ProjectFirma.Web/Controllers/ProjectAttachmentUpdateController.cs
Source/ProjectFirma.Web/Models/ProjectAttachmentUpdateModelExtensions.cs

create a copy of the file resource when starting an update; do not delete file resource on the Project when deleting an attachment on the Update; actually update the additional fields when approving an update. This pattern is now similar to how Project Images are treated.

PF-2556: fix bugs with project update attachments

---

Source/LtInfo.Common/AgGridWrappers/AgGridHtmlHelpers.cs
Source/ProjectFirma.Web/ScriptsCustom/agGrid/DropdownFilterComponent.js

adding usage of CreateEntityUrl to the ag grid implementation. A pattern not used in PF, but used in Alevin and WADNR added fix to the dropdown filter component that correctly marks the checkboxes when setting the model outside the grid. A pattern we use in Alevin to have certain filters applied on load of the grid

PF-2719 Merge mainline into Alevin - Fall 2024
